### ISSUE TITLE
[Bug] Kirki Font Control for Headings uses incorrect property "variant" instead of "font-variant"

### ISSUE THREAD

**Issue by jessecowens** [BoldGrid/boldgrid-theme-framework#453] opened 2021-07-26 22:30 UTC
**Describe the bug**
Fonts that use a different weight than "400" for their bold variant do not adjust when their variant is chosen in the customizer. This is the style that is produced:
```
<style id="kirki-postmessage-bgtfw_headings_typography">h1, .h1, h2, .h2, h3, .h3, h4, .h4, h5, .h5, h6, .h6, .bgc-heading.bgc-page-title{font-family:Old Standard TT;}h1, .h1, h2, .h2, h3, .h3, h4, .h4, h5, .h5, h6, .h6, .bgc-heading.bgc-page-title{line-height:1.1;}h1, .h1, h2, .h2, h3, .h3, h4, .h4, h5, .h5, h6, .h6, .bgc-heading.bgc-page-title{text-transform:uppercase;}h1, .h1, h2, .h2, h3, .h3, h4, .h4, h5, .h5, h6, .h6, .bgc-heading.bgc-page-title{variant:700;}h1, .h1, h2, .h2, h3, .h3, h4, .h4, h5, .h5, h6, .h6, .bgc-heading.bgc-page-title{font-style:normal;}</style>
```
The `variant:700` is not a valid CSS property, it should be `font-variant:700`

**To Reproduce**
1. Go to Customize > Fonts.
2. For the Headings, choose a Google Font that has a different variant weight, for example `Old Standart TT`
3. Select 700
4. Note that heading font weight does not change

**Expected behavior**
The inline CSS from Kirki should use `font-variant` to correctly adjust the weight of the font.

**Screenshots**
![image](https://user-images.githubusercontent.com/8019842/127067344-74dd44c2-9153-4aa1-bb94-8509d4913f7d.png)

**Comment by nicolepaschen** [comment] 2021-07-27 13:22
Duplicate of https://github.com/BoldGrid/boldgrid-theme-framework/issues/307

**Closed by nicolepaschen** 2021-07-27 13:22 UTC
